[server]
headless=true

[theme]
primaryColor="#1351b4"
base="light"
secondaryColor="#1351B4"
backgroundColor="#FDFDFD"
textColor="#262730"
font="sans serif"

[session_state]
title="Minha Aplicação Streamlit"
